### ISSUE TITLE
twitch chat

### ISSUE THREAD

**Issue by viktorblack** [neurokitti/VtuberAI#1]
is there a way to make it work with twitch chat?

**Comment by StudioMovieGirl** [comment]
Not at the moment but it could be modified too.

**Comment by StudioMovieGirl** [comment]
I am working on adapting the chat_API to work with all HF models using apply_chat_template. I am facing several issues because I delated and reinstalled windows and all my dependencies are missing like ffmpeg and cuda so I am currently just getting up and running but I will see what I can do. feal free to join the discord if you have any coding skills and whould like to help!

**Comment by viktorblack** [comment]
okay thx sadly not

**Comment by viktorblack** [comment]
a coder

**Comment by StudioMovieGirl** [comment]
ok it took a bit but I just finished the twitch implimentation im adjusting files now

**Comment by StudioMovieGirl** [comment]
OK! just updated the github repo if you need help just ask in the discord server!

**Comment by viktorblack** [comment]
oh wow nice ill try it out later today :)

**Comment by viktorblack** [comment]
oh its seems that the discord link is not working can i get a new one ?

**Comment by StudioMovieGirl** [comment]
I fixed it's! Sry it expired apparently
